[package]
name = "ben"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = { version = "0.11", features = ["color"] }
chrono = "0.4"
actix-web = "4"
reqwest = { version = "0.12", features = ["blocking", "json"] } # Or just "blocking" for synchronous, or no features for async
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"
regex = "1.11.2"

